baseURL = "https://scratch3-tello.app/"
languageCode = "en-us"
title = "Scratch3 Tello Extension"
publishDir = "docs"
canonifyurls = true
theme = "book"
googleAnalytics = "UA-188543006-1"

[params]
  BookRepo = "https://github.com/kebhr/scratch3-tello-docs"
  BookEditPath = "edit/master"

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[languages.ja]
  languageName = 'Japanese'
  contentDir = 'content.ja'
  weight = 2
